// <auto-generated />
namespace DroneAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fix_warehouse_models : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_warehouse_models));
        
        string IMigrationMetadata.Id
        {
            get { return "201612011343155_fix_warehouse_models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
